export const secondary = '#93cee1'
export const secondaryDark = '#38a5c6'
export const primary = '#99a2d3'
export const primaryDark = '#5464b5'
export const primaryBgLight = '#dee0f1'
export const textPrimary = '#333'
export const textSecondary = '#040c0f'
