export { default as Login } from './Login'
export { default as Loading } from './Loading'
export { default as Home } from './Home'
export { default as Main } from './Home/Main'
export { default as SignUp } from './SignUp'
export { default as Profile } from './Profile'
